/**
 * @file 
 * @author generated by Fraunhofer IEM
 * @brief The GlobalIdentifiers
 * @details In this file the GlobalIdentifiers are specified via preprocessor macros
 * 			 These GlobalIdentifiers are equal for all ECUs
 */
		//Define MessageType IDs
			#define MESSAGE_OVERTAKINGPERMISSIONMESSAGESREQUESTPERMISSIONOVERTAKINGPERMISSIONMESSAGESMESSAGE 1 /**< Global Identifier: For the Message-Type: requestPermission */
			#define MESSAGE_OVERTAKINGPERMISSIONMESSAGESEXECUTEDOVERTAKINGOVERTAKINGPERMISSIONMESSAGESMESSAGE 2 /**< Global Identifier: For the Message-Type: executedOvertaking */
			#define MESSAGE_OVERTAKINGCOORDINATIONMESSAGESACCEPTOVERTAKINGOVERTAKINGCOORDINATIONMESSAGESMESSAGE 3 /**< Global Identifier: For the Message-Type: acceptOvertaking */
			#define MESSAGE_OVERTAKINGCOORDINATIONMESSAGESREQUESTOVERTAKINGOVERTAKINGCOORDINATIONMESSAGESMESSAGE 4 /**< Global Identifier: For the Message-Type: requestOvertaking */
			#define MESSAGE_OVERTAKINGCOORDINATIONMESSAGESFINISHEDOVERTAKINGOVERTAKINGCOORDINATIONMESSAGESMESSAGE 5 /**< Global Identifier: For the Message-Type: finishedOvertaking */
			#define MESSAGE_OVERTAKINGPERMISSIONMESSAGESDENYPERMISSIONOVERTAKINGPERMISSIONMESSAGESMESSAGE 6 /**< Global Identifier: For the Message-Type: denyPermission */
			#define MESSAGE_OVERTAKINGPERMISSIONMESSAGESGRANTPERMISSIONOVERTAKINGPERMISSIONMESSAGESMESSAGE 7 /**< Global Identifier: For the Message-Type: grantPermission */

		//Define Port IDs
			#define PORT_FASTCARROBOCAROVERTAKINGINITIATOR1 1 /**< Global Identifier: For the Discrete-Port-Instance: overtakingInitiator1 */
			#define PORT_FASTCARROBOCAROVERTAKINGAFFILIATE1 2 /**< Global Identifier: For the Discrete-Port-Instance: overtakingAffiliate1 */
			#define PORT_DRIVECONTROLDRIVECONTROLCOMMUNICATOR1 3 /**< Global Identifier: For the Discrete-Port-Instance: communicator1 */
			#define PORT_COMMUNICATORCOORDINATORDRIVECONTROL1 4 /**< Global Identifier: For the Discrete-Port-Instance: driveControl1 */
			#define PORT_COMMUNICATORCOORDINATORCARCOORDINATOR1 5 /**< Global Identifier: For the Discrete-Port-Instance: carCoordinator1 */
			#define PORT_COMMUNICATORCOORDINATOROVERTAKINGAFFILIATE1 6 /**< Global Identifier: For the Discrete-Port-Instance: overtakingAffiliate1 */
			#define PORT_SLOWCARROBOCAROVERTAKINGINITIATOR1 7 /**< Global Identifier: For the Discrete-Port-Instance: overtakingInitiator1 */
			#define PORT_SLOWCARROBOCAROVERTAKINGAFFILIATE1 8 /**< Global Identifier: For the Discrete-Port-Instance: overtakingAffiliate1 */
			#define PORT_DRIVECONTROLDRIVECONTROLCOMMUNICATOR1 9 /**< Global Identifier: For the Discrete-Port-Instance: communicator1 */
			#define PORT_COMMUNICATORCOORDINATORCARCOORDINATOR1 10 /**< Global Identifier: For the Discrete-Port-Instance: carCoordinator1 */
			#define PORT_COMMUNICATORCOORDINATORDRIVECONTROL1 11 /**< Global Identifier: For the Discrete-Port-Instance: driveControl1 */
			#define PORT_COMMUNICATORCOORDINATOROVERTAKINGAFFILIATE1 12 /**< Global Identifier: For the Discrete-Port-Instance: overtakingAffiliate1 */
